image: ruby 2.5.3

services:
    - postgres:latest

variables:
  POSTGRES_DB: ilovepostgresql

before_script:
  - apt-get update -qq & apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
  - cp config/database.yml.gtlab config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load

deploy_staging:

  stage: deploy

  script:

    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/text-giving-staging.git

    - git push heroku master

    - echo "Deployed to staging server"

  environment:

  name: staging

  url: https://text-giving-staging.herokuapp.com/

  only:

    - master

deploy_production:

  stage: deploy

  script:

    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/text-giving.git

    - git push heroku master

    - echo "Deployed to production server"

  environment:

  name: production

  url: https://text-giving.herokuapp.com/

  when: manual

  only:

    - master
