version: '3.6'
services:
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: sebastien
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq: 
    image: sebastien
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - .:/myapp:cached
  redis:
    image: redis:latest
    volumes: 
      - redis-data:/data

volumes: 
  db-data:
  redis-data: