version: '3.3'
services:
  ilovepostgresql:
    image: postgres:10
    environment: 
    - POSTGRES_USER:"hello"
    - POSTGRES_PASSWORD:"world"
    volumes:
     - ./db-data/:/var/lib/postgresql/data
    ports:
     - "10257:5432" 
  anotherrubyapp:
    image: sebastien
    command: bundle exec rails s -p 8741 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "5532:8741"
    depends_on:
      - ilovepostgresql
      - mylocalredis
  awesomebackgroundjobs: 
    image: sebastien
    command: bundle exec sidekiq
    depends_on:
      - ilovepostgresql
      - mylocalredis
    volumes:
      - .:/myapp
  mylocalredis:
    image: redis:latest
    volumes: 
      - ./redis-data/:/data
    ports: 
      - 10247:6379